import '../globals.css'
import { Inter } from 'next/font/google'
//import BackgroundImg from '../_assets/images/flower.jpg'
const inter = Inter({ subsets: ['latin'] })
import {
    userInterface,
} from "@/_util/interface";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
    }) {    

    return (
        <div
            className="flex flex-col min-h-screen"
        >{children}</div>
  )
}
