import '@/app/globals.css'
import { Inter } from 'next/font/google'
//import BackgroundImg from '../_assets/images/flower.jpg'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
    }) {
    return (
        <div
            className="flex flex-col min-h-screen"
        >{children}</div>
  )
}
