import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import { AppContextComponent } from '@/_clientWrappers/contextWrapper';
import { SessionInterface } from '@/_util/interface';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/_util/authOptions';
import { NextAuthOptions } from "next-auth"
import ContainerWrapper from '@/_clientWrappers/containerWrapper';
import dynamic from 'next/dynamic';
import MessageComponent from '@/components/messageComponent'
import LoadingComponent from "@/components/loadingComponent"; 
import db from "@/lib/mongooseConnect"; 
const HeaderBar = dynamic(() => import("@/components/header") as any, {
    loading: () => <div className="bg-black min-h-[50px] w-full top-0">Loading...</div>,
})

export const metadata = {
  title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
    }) {
    await db.connect(); 
    let session: SessionInterface | null = await getServerSession(authOptions as NextAuthOptions); 
    let parsedSession = await JSON.parse(JSON.stringify(session)); 
    console.log("retrieved session: ", session)
    return (
        <html lang="en">
            <body
            className={`w-full h-full min-h-screen relative inset-0 bg-no-repeat bg-cover bg-center mt-[150px]`}
            >
                <AppContextComponent session={parsedSession}>
                    <ContainerWrapper>
                        <HeaderBar />
                        <MessageComponent />
                        <main className="block min-h-screen flex-col items-center">
                            {children}
                        </main>
                    </ContainerWrapper>
                </AppContextComponent>
            </body>
        </html>
    )
}
